// yes i know its bad
AddCSLuaFile("autorun/client/depthhud_radar.lua")
AddCSLuaFile("ctrlcolor.lua")
AddCSLuaFile("cl_dhradar_beacon.lua")
AddCSLuaFile("cl_dhradar_beaconspanel.lua")
AddCSLuaFile("depthhud_radar_beacon/all_npc.lua")
AddCSLuaFile("depthhud_radar_beacon/expression2.lua")
AddCSLuaFile("depthhud_radar_beacon/gmodtower_suite.lua")
AddCSLuaFile("depthhud_radar_beacon/projectiles.lua")
AddCSLuaFile("depthhud_radar_beacon/props.lua")
AddCSLuaFile("depthhud_radar_beacon/reveal.lua")
AddCSLuaFile("depthhud_radar_beacon/vehicle.lua")
AddCSLuaFile("depthhud_radar_beacon/weapons.lua")
AddCSLuaFile("depthhud_radar_beacon/znorth.lua")